server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.97.101.83:3306/imiku?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true


qiniu:
  accessKey: eQs4YJ34j5JxRkxquYS7ND7-8jr8Mj5939wcujZQ
  secretKey: 4qlQ01KnsIK7mFIObIjwgvU0WHBrVP_RnE7zKHDg
  bucket: myblog
  path: http://media.5imiku.com

logging:
  level:
    root: INFO

management:
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

